# Edit this file then run
# docker compose -f docker-compose.yaml up -d
# docker compose -f docker-compose.yaml logs -f -t
# docker compose -f docker-compose.yaml down

name: dolibarr

networks:
  network_service:
    driver: bridge
    external: true
    name: network_service
  
volumes:
  documents:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/dolibarr/documents' # The absolute path on your host
  custom:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/dolibarr/custom' # The absolute path on your host
  html:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/dolibarr/html' # The absolute path on your host

services:
  frontend:
    # Choose the version of image to install
    # dolibarr/dolibarr:latest (the latest stable version)
    # dolibarr/dolibarr:develop
    # dolibarr/dolibarr:x.y.z
    image: dolibarr/dolibarr:latest
    deploy:
      restart_policy:
        condition: always
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      DOLI_INSTALL_AUTO: "1"
      DOLI_INIT_DEMO: "0"
      DOLI_PROD: "1"
      DOLI_INSTANCE_UNIQUE_ID: "uxgscX9MtawKYZQs5G9LxkjO1xmzYYlS"
      DOLI_DB_TYPE: "mysqli"
      DOLI_DB_HOST: "mariadb.docker-host.local"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_NAME: "salatech_dolibarrdb"
      DOLI_DB_USER: "salatech_dolibarr"
      DOLI_DB_PASSWORD: "2u1Kn7j_Uc5sw74h"
      DOLI_URL_ROOT: "https://erp.salatech.vn/"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "tfmYaZiU8JNk"
      DOLI_CRON: "0"
      DOLI_CRON_KEY: "BMkdsUWnoeGx"
      DOLI_COMPANY_NAME: "CÔNG TY TNHH CÔNG NGHỆ SALA : SALA TECHNOLOGY CO., LTD"
      DOLI_COMPANY_COUNTRYCODE: "VN"
      PHP_INI_DATE_TIMEZONE: "Asia/Ho_Chi_Minh"
      PHP_INI_MEMORY_LIMIT: "256M"
      PHP_INI_UPLOAD_MAX_FILESIZE: "2M"
      PHP_INI_POST_MAX_SIZE: "8M"
      PHP_INI_ALLOW_URL_FOPEN: "0"
    networks:
      - network_service
    ports:
      - 31243:80
    extra_hosts:
      - "mariadb.docker-host.local:172.20.10.10"
    dns_search:
      - docker-host.local
    volumes:
      - html:/var/www/html
      - documents:/var/www/documents
      - custom:/var/www/html/custom