# Edit this file then run
# docker compose -f docker-compose.yaml up -d
# docker compose -f docker-compose.yaml logs -f -t
# docker compose -f docker-compose.yaml down

name: sala-docker
networks:
  network_service:
    driver: bridge
    name: network_service
    ipam:
      config:
        - subnet: 172.20.10.0/24 # The subnet for the network
          ip_range: 172.20.10.128/25 # The IP range for the network
          gateway: 172.20.10.1 # The gateway for the network

volumes:
  phpmyadmin:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/database/phpmyadmin' # The absolute path on your host

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    deploy:
      restart_policy:
        condition: no
    volumes:
      - phpmyadmin:/etc/phpmyadmin
    networks:
       network_service: null
    dns_search: 
      - docker-host.local
    ports:
      - 31633:80 # Map port 31633 on the host to port 80 in the container
    extra_hosts:
      - "mariadb.docker-host.local:172.20.10.10"
    environment:
       TZ: Asia/Ho_Chi_Minh
       PMA_ARBITRARY: "0"
       PMA_HOST: "mariadb.docker-host.local"
       PMA_PORT: "3306"