# Edit this file then run
# docker compose -f docker-compose.yml up -d
# docker compose -f docker-compose.yml logs -f -t
# docker compose -f docker-compose.yml down

name: database
volumes:
  mariadb:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/mariadb' # The absolute path on your host
  phpmyadmin:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/phpmyadmin' # The absolute path on your host

networks:
  db_network:
    driver: bridge
    name: db_network
    ipam:
      config:
        - subnet: 172.20.100.0/24 # The subnet for the network
          gateway: 172.20.100.1 # The gateway for the network

services:
  mariadb:
    # Choose the version of image to install
    # mariadb:latest (the latest stable version)
    # mariadb:11.8
    # mariadb:x.y.z

    image: mariadb:11.8
    container_name: "db-mariadb"
    deploy:
      restart_policy:
        condition: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "3wbZd-g*kv"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "0"
      MARIADB_AUTO_UPGRADE: 1
      TZ: "Asia/Ho_Chi_Minh"
    networks:
        db_network:
          ipv4_address: 172.20.100.10 # The static IP address for the container
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    deploy:
      restart_policy:
        condition: no
    volumes:
      - phpmyadmin:/etc/phpmyadmin
    networks:
      - db_network
    ports:
      - 31633:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db-mariadb # The hostname of the database container
      - PMA_PORT=3306 # The port of the database container
    depends_on:
      - mariadb