# Edit this file then run
# docker compose -f docker-compose.yaml up -d
# docker compose -f docker-compose.yaml logs -f -t
# docker compose -f docker-compose.yaml down

name: database

networks:
  network_service:
    driver: bridge
    name: network_service
    external: true
          
volumes:
  mariadb:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/database/mariadb' # The absolute path on your host
  # mssql:
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/var/database/mssql' # The absolute path on your host
  # redis-queue:
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/var/database/redis-queue' # The absolute path on your host
  # redis-cache:
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/var/database/redis-cache' # The absolute path on your host

services:
  # Choose the version of image to install
  # mariadb:latest (the latest stable version)
  # mariadb:11.8
  # mariadb:x.y.z
  mariadb:
    image: mariadb:11.8
    container_name: "mariadb"
    deploy:
      restart_policy:
        condition: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_ROOT_PASSWORD: "3wbZd-g*kv" # For compatibility with both MySQL and MariaDB images
      MARIADB_ROOT_PASSWORD: "3wbZd-g*kv" # For compatibility with both MySQL and MariaDB images
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "0"
      MARIADB_AUTO_UPGRADE: 1
    networks:
        network_service:
          ipv4_address: 172.20.10.10 # The static IP address for the container
    dns_search: 
      - docker-host.local
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  # redis-queue:
  #   image: redis:6.2-alpine
  #   container_name: redis-queue
  #   networks:
  #     network_service: 
  #       ipv4_address: 172.20.10.11 # The static IP address for the container
  #   dns_search: 
  #     - docker-host.local
  #   deploy:
  #     restart_policy:
  #       condition: always
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
  #   volumes:
  #     - redis-queue:/data
  #   environment:
  #      TZ: Asia/Ho_Chi_Minh

  # redis-cache:
  #   image: redis:6.2-alpine
  #   container_name: redis-cache
  #   networks:
  #     network_service: 
  #       ipv4_address: 172.20.10.12 # The static IP address for the container
  #   dns_search: 
  #     - docker-host.local
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
  #   deploy:
  #     restart_policy:
  #       condition: always
  #   volumes:
  #     - redis-cache:/data
  #   environment:
  #      TZ: Asia/Ho_Chi_Minh

  # Choose the version of image to install
  # mcr.microsoft.com/mssql/server:2022-latest (the latest stable version)
  # mcr.microsoft.com/mssql/server:2019-latest
  # mcr.microsoft.com/mssql/server:x.y.z
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: "mssql-server"
  #   deploy:
  #     restart_policy:
  #       condition: always
  #   volumes:
  #     - mssql:/var/opt/mssql
  #   environment:
  #     TZ: "Asia/Ho_Chi_Minh"
  #     MSSQL_SA_PASSWORD: "3wbZd-g*kv"
  #     ACCEPT_EULA: "Y"
  #     MSSQL_PID: "Standard"
  #   networks:
  #     - network_service
  #   ports:
  #     - 1433:1433
  #   healthcheck:
  #     test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "3wbZd-g*kv" -C -Q "SELECT 1" -b -o /dev/null || exit 1
  #     start_period: 20s
  #     interval: 20s
  #     timeout: 5s
  #     retries: 5
