# Edit this file then run
# docker compose -f docker-compose.yml up -d
# docker compose -f docker-compose.yml logs -f -t
# docker compose -f docker-compose.yml down

name: database
volumes:
  mariadb:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/mariadb' # The absolute path on your host
  phpmyadmin:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/phpmyadmin' # The absolute path on your host
  mssql:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/mssql' # The absolute path on your host
  redis-queue:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/redis-queue' # The absolute path on your host
  redis-cache:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/redis-cache' # The absolute path on your host
  postgresql:
    #driver_opts:
      #type: 'none'
      #o: 'bind'
      #device: '/var/database/postgresql' # The absolute path on your host

networks:
  network_db:
    driver: bridge
    name: network_db
    ipam:
      config:
        - subnet: 172.20.100.0/24 # The subnet for the network
          ip_range: 172.20.100.128/25 # The IP range for the network
          gateway: 172.20.100.1 # The gateway for the network

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    deploy:
      restart_policy:
        condition: no
    volumes:
      - phpmyadmin:/etc/phpmyadmin
    networks:
       network_db: null
    dns_search: 
      - docker-host.local
    ports:
      - 31633:80
    extra_hosts:
      - "mariadb.docker-host.local:172.20.100.10"
    environment:
       TZ: Asia/Ho_Chi_Minh
       PMA_ARBITRARY: "0"
       PMA_HOST: "mariadb.docker-host.local"
       PMA_PORT: "3306"
    depends_on:
      - mariadb

  mariadb:
    # Choose the version of image to install
    # mariadb:latest (the latest stable version)
    # mariadb:11.8
    # mariadb:x.y.z
    image: mariadb:11.8
    container_name: "mariadb"
    deploy:
      restart_policy:
        condition: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "3wbZd-g*kv" # For compatibility with both MySQL and MariaDB images
      MARIADB_ROOT_PASSWORD: "3wbZd-g*kv" # For compatibility with both MySQL and MariaDB images
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "0"
      MARIADB_AUTO_UPGRADE: 1
      TZ: "Asia/Ho_Chi_Minh"
    networks:
        network_db:
          ipv4_address: 172.20.100.10 # The static IP address for the container
    dns_search: 
      - docker-host.local
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  redis-queue:
    image: redis:6.2-alpine
    container_name: redis-queue
    networks:
      network_db: 
        ipv4_address: 172.20.100.11 # The static IP address for the container
    dns_search: 
      - docker-host.local
    deploy:
      restart_policy:
        condition: always
    volumes:
      - redis-queue:/data
    environment:
       TZ: Asia/Ho_Chi_Minh

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    networks:
      network_db: 
        ipv4_address: 172.20.100.12 # The static IP address for the container
    dns_search: 
      - docker-host.local
    deploy:
      restart_policy:
        condition: always
    volumes:
      - redis-cache:/data
    environment:
       TZ: Asia/Ho_Chi_Minh